import "./globals.css";
import { Zen_Kaku_Gothic_Antique } from "next/font/google";
import { Web3ModalProvider } from "@/context";

export const gothic = Zen_Kaku_Gothic_Antique({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <Web3ModalProvider>{children}</Web3ModalProvider>
      </body>
    </html>
  );
}
